name: Build on all supported platforms

on:
  workflow_call:
    inputs:
      build-type:
        description: The build type. Can be one of "Debug" or "Release". Defaults to "Release".
        type: string
        required: true
        default: Release
      store-output:
        description: Whether the build should be stored. (Useful for release builds). Defaults to false.
        type: boolean
        required: true
        default: false

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      build-type: ${{ inputs.build-type }}
      store-output: ${{ inputs.store-output }}
