name: Build on Windows

on:
  workflow_call:
    inputs:
      build-type:
        description: 'The build type. Can be one of "Debug" or "Release". Defaults to "Release"'
        type: string
        required: false
        default: 'Release'

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        arch:
          - amd64
          - amd64_x86
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          vsversion: 2022
      - name: "Create build directory"
        run: |
          mkdir build
          cd build
          chdir
      - name: "Run CMake"
        run: |
          cmake.exe -G "Visual Studio 17 2022" ../
      - name: "Run MSBuild"
        run: |
          MSBuild.exe /m /p:Configuration=${{ inputs.build-type }} .\browsercontrol.sln

