name: Build on push

# Simply build the library on all supported platforms
# when pushing to non-release branches

on: [push]

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      build-type: 'Release'
      store-output: false
