name: Build all supported platforms

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'The build type. Can be one of "Debug" or "Release". Defaults to "Release"'
        type: string
        required: false
        default: 'Release'

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      build-type: ${{ inputs.build-type }}
