name: Build on Windows

on:
  workflow_call:
    inputs:
      build-type:
        description: The build type. Can be one of "Debug" or "Release". Defaults to "Release".
        type: string
        required: true
        default: Release
      store-output:
        description: Whether the build should be stored. (Useful for release builds). Defaults to false.
        type: boolean
        required: true
        default: false

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x64
          - win32
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - uses: actions/setup-java@v4
        with:
          # Rewrite 'win32' as 'x86'
          architecture: ${{ matrix.arch == 'win32' && 'x86' || matrix.arch }}
          distribution: temurin
          java-version: 17
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          vsversion: 2022
      - uses: nuget/setup-nuget@v1
      - name: Build browsercontrol library
        run: |
          mkdir .\build
          cd .\build\
          cmake.exe -A "${{ matrix.arch }}" ..\
          MSBuild.exe /m /p:Configuration=${{ inputs.build-type }} /p:Platform=${{ matrix.arch }} .\browsercontrol.sln
      - name: Package assets
        if: ${{ inputs.store-output }}
        id: package-assets
        working-directory: ${{ github.workspace }}/build/output/${{ inputs.build-type }}
        shell: pwsh
        run: |
          jar.exe cf browsercontrol.jar .\*.dll

          $checksum = (python ${{ github.workspace}}\scripts\checksum.py browsercontrol.jar) | Out-String -NoNewline

          Move-Item "browsercontrol.jar" "${{ github.workspace}}\build\output\browsercontrol_0_${{ matrix.arch == 'win32' && '0' || '1' }}_$checksum.jar"
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.store-output }}
        with:
          name: windows-${{ matrix.arch }}
          path: ${{ github.workspace }}/build/output/browsercontrol*.jar
          if-no-files-found: error
