name: Build on Windows

on:
  workflow_call:
    inputs:
      build-type:
        description: 'The build type. Can be one of "Debug" or "Release". Defaults to "Release"'
        type: string
        required: false
        default: 'Release'

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        arch:
          - amd64_x86
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          vsversion: 2022
      - uses: nuget/setup-nuget@v1
      - name: "Build browsercontrol.dll"
        run: |
          mkdir .\build
          cd .\build\
          cmake.exe -G "Visual Studio 17 2022" ..\
          MSBuild.exe /m .\browsercontrol.sln

