name: Build on push

# Simply build the library on all supported platforms
# when pushing to non-release branches

on:
  push:
    branches-ignore:
      - 'release/**'
      - 'master'

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml
