name: Create a release upon pushing new tags

# Upon pushes to release branches or master we will create
# a new release if there have been changes to the META
# file.
on:
  push:
    tags:
      - v*

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Validate versions
        id: validate-version
        run: |
          if [[ "${{ github.ref_name }}" != "$(cat META)" ]]; then
            echo "
            ===============================================================
            Invalid version detected!
            ===============================================================
            Git tag is \"${{ github.ref_name }}\"
            ./META is \"$(cat META)\"
            ===============================================================
            "
            exit 1
          fi
  build-windows:
    needs: [version-check]
    uses: ./.github/workflows/build-windows.yml
    with:
      build-type: Release
      store-output: true
  release-browsercontrol:
    needs: [build-windows, version-check]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/artifacts/
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/artifacts/windows-*/*.zip
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
