name: Create a release upon push to master.

# Upon pushes to release branches or master we will create
# a new release if there have been changes to the META
# file.
on:
  push:
    # TODO: Update to only fire on release and master branches with modified 'META' file

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      build-type: 'Release'
      store-output: true
