name: Create a release upon push to master.

# Upon pushes to release branches or master we will create
# a new release if there have been changes to the META
# file.
on:
  push:
    # TODO: Update to only fire on release and master branches with modified 'META' file

jobs:
  release-browsercontrol:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Define versions
        id: version
        run: |
          echo "GIT_TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "META_VERSION=$(cat META)" >> $GITHUB_OUTPUT
      - name: Build on Windows
        uses: ./.github/workflows/build-windows.yml
        with:
          build-type: 'Release'
          store-output: true
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/artifacts/
      - name: List artifacts
        id: list-artifacts
        run: |
          ls -la
          ls -la ${{ github.workspace }}/artifacts/
