name: Create a release upon push to master.

# Upon pushes to release branches or master we will create
# a new release if there have been changes to the META
# file.
on:
  push:
    # TODO: Update to only fire on release and master branches with modified 'META' file

jobs:
  release-browsercontrol:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Define versions
        id: version
        run: |
          echo "GIT_TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "META_VERSION=$(cat META)" >> $GITHUB_OUTPUT
      - name: Validate version
        id: validate-version
        if: ${{ needs.version.outputs.GIT_TAG }} != ${{ needs.version.outputs.META_VERSION }}
        run: |
          echo "
          ===============================================================
          Invalid version detected!
          ===============================================================
          ./META is \"${{ needs.version.outputs.META_VERSION }}\"
          Git tag is \"${{ needs.version.outputs.GIT_TAG }}\"
          ===============================================================
          "
          exit 1
      - name: Build on Windows
        uses: ./.github/workflows/build-windows.yml
        with:
          build-type: 'Release'
          store-output: true
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/windows-*"
          artifactErrorsFailBuild: true
          draft: true
          generateReleaseNotes: true
          tag: v${{ needs.version.outputs.GIT_TAG }}
