name: Create a release upon push to master.

# Upon pushes to release branches or master we will create
# a new release if there have been changes to the META
# file.
on:
  push:
    # TODO: Update to only fire on release and master branches with modified 'META' file

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Define outputs
        id: define-version
        run: |
          echo "META_VERSION=$(cat META)" >> $GITHUB_OUTPUT
      - name: Validate versions
        id: validate-version
        run: |
          if [[ "${{ github.ref_name }}" != "${{ steps.version.outputs.META_VERSION }}" ]]; then
            echo "
            ===============================================================
            Invalid version detected!
            ===============================================================
            Git tag is \"${{ github.ref_name }}\"
            ./META is \"${{ steps.version.outputs.META_VERSION }}\"
            ===============================================================
            "
            echo "SHOULD EXIT 1"
          fi
  build-windows:
    needs: [version-check]
    uses: ./.github/workflows/build-windows.yml
    with:
      build-type: 'Release'
      store-output: true
  release-browsercontrol:
    needs: [build-windows, version-check]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/artifacts/
      - name: List artifacts
        id: list-artifacts
        run: |
          ls -la
          ls -la ${{ github.workspace }}/artifacts/
